import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url)), PORT=Number(process.env.PORT||3000), cg='https://api.coingecko.com/api/v3', binance='https://fapi.binance.com/fapi/v1', fear='https://api.alternative.me/fng/?limit=1', cache=new Map(), headers={accept:'application/json','user-agent':'CryptoPulse/0.2'};
async function jsonFetch(url,ttl=30000){const old=cache.get(url);if(old&&Date.now()-old.at<ttl)return old.value;let r=await fetch(url,{headers});if(!r.ok&&r.status===429){if(old)return old.value;await new Promise(x=>setTimeout(x,700));r=await fetch(url,{headers})}if(!r.ok)throw Error(`upstream ${r.status}`);const v=await r.json();cache.set(url,{at:Date.now(),value:v});return v}
function ema(a,n){const k=2/(n+1);let e=a[0]||0;return a.map((v,i)=>i?(e=v*k+e*(1-k)):(e=v))} function rsi(a,n=14){let g=0,l=0;for(let i=1;i<=n&&i<a.length;i++){let d=a[i]-a[i-1];d>=0?g+=d:l-=d}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){let d=a[i]-a[i-1];ag=(ag*(n-1)+(d>0?d:0))/n;al=(al*(n-1)+(d<0?-d:0))/n}return al?100-100/(1+ag/al):100}
function analyze(p){const price=p.at(-1)||0,e20=ema(p,20).at(-1),e50=ema(p,50).at(-1),rr=rsi(p),f=ema(p,12),s=ema(p,26),mom=f.at(-1)-s.at(-1)>f.at(-2)-s.at(-2);let score=50,reasons=[];if(price>e20&&e20>e50){score+=18;reasons.push('Price above EMA20/EMA50.')}else{score-=16;reasons.push('Price below EMA20/EMA50.')}if(rr>=55&&rr<=72){score+=12;reasons.push(`RSI ${rr.toFixed(0)} supports momentum.`)}else if(rr>72){score-=8;reasons.push(`RSI ${rr.toFixed(0)} is overheated.`)}else{score-=8;reasons.push(`RSI ${rr.toFixed(0)} is weak.`)}score+=mom?10:-8;return{score:Math.max(0,Math.min(100,Math.round(score))),label:score>=68?'BUY':score<=38?'AVOID':'HOLD',rsi:rr,ema20:e20,ema50:e50,reasons}}
function candles(raw){return raw.map(x=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}))}
function smc(cs,biasCs=cs,midCs=cs){
 const c=cs.at(-1),recent=cs.slice(-40),prev=cs.slice(-25,-1),prior=cs.slice(-576,-288),day=cs.slice(-288);const pdl=Math.min(...(prior.length?prior:day).map(x=>x.l)),pdh=Math.max(...(prior.length?prior:day).map(x=>x.h));
 const lows=recent.slice(0,-3).map(x=>x.l),highs=recent.slice(0,-3).map(x=>x.h),eqLow=Math.min(...lows),eqHigh=Math.max(...highs),tol=c.c*.0015;
 const bullSweep=c.l<pdl&&c.c>pdl||lows.some(x=>Math.abs(x-eqLow)<tol)&&c.l<eqLow&&c.c>eqLow;
 const bearSweep=c.h>pdh&&c.c<pdh||highs.some(x=>Math.abs(x-eqHigh)<tol)&&c.h>eqHigh&&c.c<eqHigh;
 const body=Math.abs(c.c-c.o)||c.c*.0001,lower=Math.min(c.o,c.c)-c.l,upper=c.h-Math.max(c.o,c.c),bullReject=lower>body*1.4&&c.c>c.l+(c.h-c.l)*.62,bearReject=upper>body*1.4&&c.c<c.l+(c.h-c.l)*.38;
 const swingHigh=Math.max(...prev.slice(-8).map(x=>x.h)),swingLow=Math.min(...prev.slice(-8).map(x=>x.l)),bullMss=c.c>swingHigh,bearMss=c.c<swingLow;
 const a=cs.at(-3),bb=cs.at(-2),fvgBull=bb.l>a.h,fvgBear=bb.h<a.l,bullZone=fvgBull?{low:a.h,high:bb.l}:null,bearZone=fvgBear?{low:bb.h,high:a.l}:null;
 const rangeHigh=Math.max(...recent.map(x=>x.h)),rangeLow=Math.min(...recent.map(x=>x.l)),mid=rangeLow+(rangeHigh-rangeLow)*.5,discount=c.c<=mid,premium=c.c>=mid;
 const biasClose=biasCs.at(-1)?.c||c.c,biasEma=ema(biasCs.map(x=>x.c),50).at(-1),biasBull=biasClose>biasEma;
 const midCandle=midCs.at(-1)||c,midPrev=midCs.at(-2)||midCandle,midRange=Math.max(...midCs.slice(-24).map(x=>x.h))-Math.min(...midCs.slice(-24).map(x=>x.l))||c.c*.01,midLow=Math.min(...midCs.slice(-24).map(x=>x.l)),midHigh=Math.max(...midCs.slice(-24).map(x=>x.h)),midSweepBull=midCandle.l<midLow+midRange*.12&&midCandle.c>midCandle.o,midSweepBear=midCandle.h>midHigh-midRange*.12&&midCandle.c<midCandle.o,avgVol=cs.slice(-21,-1).reduce((a,x)=>a+x.v,0)/Math.max(1,cs.slice(-21,-1).length),volRatio=avgVol?c.v/avgVol:0,volSpike=volRatio>=1.5,mssLevel=biasBull?swingHigh:swingLow,fvgLow=fvgBull?a.h*.999:rangeLow+(rangeHigh-rangeLow)*.38,fvgHigh=fvgBull?bb.l*1.001:rangeLow+(rangeHigh-rangeLow)*.45;
 const bullEntry=discount&&(!!bullZone||fvgBull),bearEntry=premium&&(!!bearZone||fvgBear);
 const longChecks=[biasBull,bullSweep,bullSweep,bullMss,bullEntry,bullReject,bullMss,!!bullZone,bullEntry&&bullSweep,bullSweep];
 const shortChecks=[!biasBull,bearSweep,bearSweep,bearMss,bearEntry,bearReject,bearMss,!!bearZone,bearEntry&&bearSweep,bearSweep];
 const item=(ok,yes,no)=>({status:ok?'PASS':'WAIT',detail:ok?yes:no});
 const longChecklist=[item(biasBull,'1H bullish bias aligned','1H bias is not bullish'),item(bullSweep,'PDL / equal lows swept and reclaimed','No bullish liquidity sweep'),item(bullSweep,'Sell-side liquidity taken','Sell-side sweep not confirmed'),item(bullMss,'5m bullish MSS above swing high','5m bullish MSS not confirmed'),item(bullEntry,'Discount / bullish OTE-FVG entry zone','Not in bullish discount/OTE-FVG'),item(bullReject,'Green rejection wick / fast reversal','No bullish rejection wick'),item(bullMss,'Bullish structure break confirmed','Bullish structure break absent'),item(!!bullZone,'Bullish FVG identified','No clean bullish FVG'),item(bullEntry&&bullSweep,'LONG confluence is present','LONG confluence incomplete'),item(bullSweep,'SL can sit below sweep wick','Validate SL below sweep wick')];
 const shortChecklist=[item(!biasBull,'1H bearish bias aligned','1H bias is not bearish'),item(bearSweep,'PDH / equal highs swept and rejected','No bearish liquidity sweep'),item(bearSweep,'Buy-side liquidity taken','Buy-side sweep not confirmed'),item(bearMss,'5m bearish MSS below swing low','5m bearish MSS not confirmed'),item(bearEntry,'Premium / bearish OTE-FVG entry zone','Not in bearish premium/OTE-FVG'),item(bearReject,'Red rejection wick / fast reversal','No bearish rejection wick'),item(bearMss,'Bearish structure break confirmed','Bearish structure break absent'),item(!!bearZone,'Bearish FVG identified','No clean bearish FVG'),item(bearEntry&&bearSweep,'SHORT confluence is present','SHORT confluence incomplete'),item(bearSweep,'SL can sit above sweep wick','Validate SL above sweep wick')];
 const longScore=longChecks.filter(Boolean).length*10,shortScore=shortChecks.filter(Boolean).length*10,longEntry=bullZone?(bullZone.low+bullZone.high)/2:rangeLow+(rangeHigh-rangeLow)*.382,shortEntry=bearZone?(bearZone.low+bearZone.high)/2:rangeLow+(rangeHigh-rangeLow)*.618,longSl=Math.min(c.l,eqLow)*.998,shortSl=Math.max(c.h,eqHigh)*1.002,longRisk=Math.abs(longEntry-longSl),shortRisk=Math.abs(shortSl-shortEntry);
 const setup=(side,score,checklist,entry,sl,risk,zone,liquidity)=>({side,score,confidence:score,direction:score>=70?(side==='LONG'?'LONG':'SHORT'):'WAIT',entry,sl,tp1:side==='LONG'?entry+risk*2:entry-risk*2,tp2:side==='LONG'?entry+risk*3:entry-risk*3,rr:2,zone:zone?`${side==='LONG'?'Bullish':'Bearish'} OTE / FVG`:'No confirmed OTE / FVG',liquidity,checklist});
 const long=setup('LONG',longScore,longChecklist,longEntry,longSl,longRisk,bullZone,bullSweep),short=setup('SHORT',shortScore,shortChecklist,shortEntry,shortSl,shortRisk,bearZone,bearSweep),accountDefault=1000,riskPercent=1,longUnits=longRisk?(accountDefault*riskPercent/100)/longRisk:0,shortUnits=shortRisk?(accountDefault*riskPercent/100)/shortRisk:0,invLong=longSl,invShort=shortSl;
 const direction=longScore>=70&&longScore>shortScore?'LONG':shortScore>=70&&shortScore>longScore?'SHORT':'WAIT',score=Math.max(longScore,shortScore);
 const advanced={A1:{label:'15m wick sweep close hold',status:(midSweepBull||midSweepBear)?'PASS':'WAIT',detail:(midSweepBull||midSweepBear)?'15m sweep wick and close-hold detected':'No confirmed 15m wick sweep close-hold'},A2:{label:'5m MSS / CHOCH level',status:(bullMss||bearMss)?'PASS':'WAIT',level:mssLevel,detail:`Exact swing break level ${mssLevel}`},A3:{label:'Volume spike & shift',status:volSpike?'PASS':'WAIT',ratio:Number(volRatio.toFixed(2)),detail:`Volume ${volRatio.toFixed(2)}× average (gate ≥1.50×)`},A4:{label:'5m FVG entry band',status:(fvgBull||fvgBear)?'PASS':'WAIT',low:fvgLow,high:fvgHigh,detail:`Buffered band ${fvgLow.toFixed(6)} – ${fvgHigh.toFixed(6)}`},A5:{label:'Invalidation / SL level',status:'PASS',long:invLong,short:invShort,detail:`LONG invalidation ${invLong.toFixed(6)} · SHORT invalidation ${invShort.toFixed(6)}`},A6:{label:'Risk calculation',status:'PASS',account:accountDefault,riskPercent, longUnits,shortUnits,detail:`1% risk · LONG ${longUnits.toFixed(4)} units · SHORT ${shortUnits.toFixed(4)} units`}};
 return{timeframe:'5m execution · 1h bias',direction,score,confidence:score,price:c.c,dailyBias:biasBull?'BULLISH':'BEARISH',liquidity:{pdl,pdh,equalLow:eqLow,equalHigh:eqHigh,bullishSweep:bullSweep,bearishSweep:bearSweep,swept:bullSweep||bearSweep},entry:{current:c.c,bullish:long.entry,bearish:short.entry,zone:long.zone||short.zone,fvg:fvgBull?'Bullish FVG':fvgBear?'Bearish FVG':'None',rangeLow,rangeHigh},risk:{sl:direction==='SHORT'?short.sl:long.sl,tp1:direction==='SHORT'?short.tp1:long.tp1,tp2:direction==='SHORT'?short.tp2:long.tp2,rr:2},setups:{long,short},charts:{context:cs.slice(-80),execution:cs.slice(-60),bias:biasCs.slice(-60)},checklist:direction==='SHORT'?shortChecklist:longChecklist,advanced,note:'LONG and SHORT are scored independently from live Binance candles. WAIT means neither side has enough confirmation.'}
}
const idsToSymbols=new Map(); function tickerMarkets(tickers){return tickers.filter(x=>/USDT$/.test(x.symbol)).sort((a,b)=>(+b.quoteVolume||0)-(+a.quoteVolume||0)).slice(0,100).map((x,i)=>({id:x.symbol.replace(/USDT$/,'').toLowerCase(),symbol:x.symbol.replace(/USDT$/,''),name:x.symbol.replace(/USDT$/,''),market_cap_rank:i+1,current_price:+x.lastPrice,price_change_percentage_24h:+x.priceChangePercent,sparkline_in_7d:{price:[]}}))} async function dashboard(coin='bitcoin',days='30',fast='0'){if(fast==='1'){const markets=tickerMarkets(await jsonFetch(`${binance}/ticker/24hr`,30000));markets.forEach(m=>idsToSymbols.set(m.id,(m.symbol||'').toUpperCase()));const enriched=markets.map(m=>({...m,bulkAnalysis:analyze([])}));return{updatedAt:new Date().toISOString(),markets:enriched,selected:coin,chart:[],analysis:null,smc:null,fearGreed:null,availability:{marketData:'live · Binance Futures',smc:'loading in background',fearGreed:'loading'}}}let markets;try{markets=await jsonFetch(`${cg}/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=true&price_change_percentage=24h,7d`)}catch(e){const tickers=await jsonFetch(`${binance}/ticker/24hr`,30000);markets=tickerMarkets(tickers)}markets.forEach(m=>idsToSymbols.set(m.id,(m.symbol||'').toUpperCase()));const enriched=markets.map(m=>({...m,bulkAnalysis:analyze((m.sparkline_in_7d?.price||[]).filter(Number.isFinite))}));if(fast==='1')return{updatedAt:new Date().toISOString(),markets:enriched,selected:coin,chart:[],analysis:null,smc:null,fearGreed:null,availability:{marketData:'live · CoinGecko',smc:'loading in background',fearGreed:'loading'}};const chart=await jsonFetch(`${cg}/coins/${encodeURIComponent(coin)}/market_chart?vs_currency=usd&days=${days}&interval=daily`);let smcData=null;try{const sym=idsToSymbols.get(coin)||'BTC';smcData=await smcFor(sym)}catch(e){smcData={error:'5m SMC data unavailable for this symbol'}}let fg=null;try{fg=(await jsonFetch(fear,60000)).data?.[0]||null}catch{}const prices=(chart.prices||[]).map(x=>x[1]);return{updatedAt:new Date().toISOString(),markets:enriched,selected:coin,chart:prices.slice(-90),analysis:analyze(prices),smc:smcData,fearGreed:fg,availability:{marketData:'live · CoinGecko',smc:'live · Binance 5m/1h',fearGreed:fg?'live · Alternative.me':'unavailable'}}}
async function futuresSymbols(){const d=await jsonFetch('https://fapi.binance.com/fapi/v1/exchangeInfo',300000);return (d.symbols||[]).filter(x=>x.status==='TRADING'&&['USDT','USDC'].includes(x.quoteAsset)&&x.contractType==='PERPETUAL').map(x=>({symbol:x.baseAsset,contract:x.symbol,quote:x.quoteAsset})).sort((a,b)=>a.symbol.localeCompare(b.symbol))}
async function smcFor(symbol){const sym=/(USDT|USDC)$/i.test(symbol)?symbol:`${symbol}USDT`;const [m5,h1,m15]=await Promise.all([jsonFetch(`${binance}/klines?symbol=${sym}&interval=5m&limit=600`,15000),jsonFetch(`${binance}/klines?symbol=${sym}&interval=1h&limit=300`,30000),jsonFetch(`${binance}/klines?symbol=${sym}&interval=15m&limit=300`,20000)]);return smc(candles(m5),candles(h1),candles(m15))}
async function scanSmc(markets){const out=[];for(let i=0;i<markets.length;i+=8){const batch=markets.slice(i,i+8);const rows=await Promise.all(batch.map(async m=>{try{return{...m,smc:await smcFor((m.symbol||'').toUpperCase())}}catch(e){return{...m,smc:{direction:'UNAVAILABLE',score:0,error:'Pair unavailable'}}}}));out.push(...rows)}return out.sort((a,b)=>(b.smc?.score||0)-(a.smc?.score||0))}
function send(res,s,d,type='application/json'){res.writeHead(s,{'content-type':type,'cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(d):d)}async function handler(req,res){try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/dashboard')return send(res,200,await dashboard(u.searchParams.get('coin')||'bitcoin',u.searchParams.get('days')||'30',u.searchParams.get('fast')||'0'));if(u.pathname==='/api/smc'){try{return send(res,200,await smcFor(u.searchParams.get('symbol')||'BTC'))}catch(e){return send(res,200,{error:'Futures pair unavailable',detail:e.message})}}if(u.pathname==='/api/smc-scan'){const ms=await jsonFetch(`${cg}/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1`,60000);return send(res,200,{updatedAt:new Date().toISOString(),rows:await scanSmc(ms)})}if(u.pathname==='/api/futures-symbols')return send(res,200,{updatedAt:new Date().toISOString(),symbols:await futuresSymbols()});if(u.pathname==='/api/health')return send(res,200,{ok:true});if(u.pathname==='/favicon.ico'){res.writeHead(204);return res.end()}const p=u.pathname==='/'?'/index.html':u.pathname,b=await readFile(join(root,'public',p)),type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'}[extname(p)]||'application/octet-stream';return send(res,200,b,type)}catch(e){console.error(e);send(res,500,{error:'Data temporarily unavailable',detail:e.message})}}http.createServer(handler).listen(PORT,'0.0.0.0',()=>console.log(`CryptoPulse SMC listening on ${PORT}`));
